__all__ = [
    'STATE_ABORTED',
    'STATE_FAILED',
    'STATE_FINISHED',
    'STATE_RUNNING',
    'STATE_STARTED',
    'STATE_STOPPED',
]

# The various statuses
STATE_ABORTED = 'ABORTED'
STATE_FAILED = 'FAILED'
STATE_FINISHED = 'FINISHED'
STATE_RUNNING = 'RUNNING'
STATE_STARTED = 'STARTED'
STATE_STOPPED = 'STOPPED'
