#!/usr/bin/env bash

# cd to the top level directory of this archive
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd $dir/../..

# execute the regeneration script
PYTHONPATH='.' python3 httpobs/scanner/utils.py
