# The various statuses
STATE_ABORTED = 'ABORTED'
STATE_FAILED = 'FAILED'
STATE_FINISHED = 'FINISHED'
STATE_PENDING = 'PENDING'
STATE_STARTING = 'STARTING'
STATE_RUNNING = 'RUNNING'

__all__ = [
    'NUM_TESTS',
    'STATE_ABORTED',
    'STATE_FAILED',
    'STATE_FINISHED',
    'STATE_PENDING,'
    'STATE_RUNNING',
    'STATE_STARTING',
]
