# The number of tests in the scanner
NUM_TESTS = 11

# The various statuses
STATE_ABORTED = 'ABORTED'
STATE_FAILED = 'FAILED'
STATE_FINISHED = 'FINISHED'
STATE_PENDING = 'PENDING'
STATE_RUNNING = 'RUNNING'
STATE_STARTED = 'STARTED'
STATE_STOPPED = 'STOPPED'

__all__ = [
    'NUM_TESTS',
    'STATE_ABORTED',
    'STATE_FAILED',
    'STATE_FINISHED',
    'STATE_PENDING,'
    'STATE_RUNNING',
    'STATE_STARTED',
    'STATE_STOPPED',
]