on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Run tests

jobs:
  test:
    name: lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    env:
      HTTPOBS_DATABASE_HOST: fakehost
      HTTPOBS_DATABASE_PASS: foo
      HTTPOBS_DATABASE_USER: bar
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - run: poetry install

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit against all files
        run: poetry run pre-commit run --all-files

      - name: Run nose tests
        run: poetry run nosetests httpobs/tests --with-coverage --cover-package=httpobs
